// Generates LLM-friendly routes from lib/notes.json + a few hard-coded site
// facts. Runs as a prebuild step (npm run build). Files written here are
// gitignored — see .gitignore "LLM plugin generated files" block.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const SITE_URL = "https://nicolasfry.com";
const SITE_NAME = "Nicolas Fry";
const SITE_DESC =
  "Software engineer and founder building TurboDocx, writing from the South Florida coast on building, distribution, and engineering craft.";

const notes = JSON.parse(
  readFileSync(resolve(root, "lib/notes.json"), "utf8"),
);

const ELSEWHERE = [
  {
    title: "TurboDocx",
    url: "https://www.turbodocx.com",
    description: "AI-powered document automation platform I'm building",
  },
  { title: "GitHub", url: "https://github.com/nicolasiscoding" },
  { title: "X / Twitter", url: "https://x.com/NicolasBuilds" },
  { title: "LinkedIn", url: "https://www.linkedin.com/in/nicolasfry" },
];

function write(relPath, content) {
  const full = resolve(root, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
  console.log(`  ✓ ${relPath}`);
}

// JS string literal — escape backslash, backtick, and ${ for template safety.
function js(s) {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function noteUrl(slug) {
  return `${SITE_URL}/notes/${slug}`;
}

function noteMarkdown(note) {
  // Until real bodies land, emit metadata + blurb in a clean MD shell.
  // When MDX/MD bodies exist, swap this for the real content.
  return `---
title: ${note.title}
url: ${noteUrl(note.slug)}
date: ${note.date}
topic: ${note.topic}
read: ${note.read}
---

# ${note.title}

> ${note.blurb}

*Filed ${note.date} · ${note.read}*

---

_Full content lands soon. Until then, this is a placeholder generated from
the note's title, blurb, and metadata._
`;
}

function homeMarkdown() {
  return `---
title: ${SITE_NAME} — Founder, TurboDocx · Writing from South Florida
url: ${SITE_URL}/
---

# ${SITE_NAME}

> ${SITE_DESC}

## About

Software engineer by craft, founder by trade, technology enthusiast by
practice. Currently building [TurboDocx](https://www.turbodocx.com) and
writing from the South Florida coast.

**Now**: Founder, TurboDocx
**Before**: Startups, Okta/Auth0, Citrix, FlexShopper, UKG
**Where**: Somewhere between Palm Beach County and Miami-Dade
**Status**: Heads down, building

## Notes

${notes
  .slice(0, 5)
  .map((n) => `- [${n.title}](${noteUrl(n.slug)}) — ${n.blurb}`)
  .join("\n")}

[All notes](${SITE_URL}/notes)

## Elsewhere

${ELSEWHERE.map((e) => `- [${e.title}](${e.url})`).join("\n")}
`;
}

function notesArchiveMarkdown() {
  return `---
title: Notes — ${SITE_NAME}
url: ${SITE_URL}/notes
---

# Notes

> ${SITE_DESC}

${notes
  .map(
    (n) =>
      `- [${n.title}](${noteUrl(n.slug)}) — ${n.blurb} _(${n.date} · ${n.read})_`,
  )
  .join("\n")}
`;
}

function llmsTxt() {
  return `# ${SITE_NAME}

> ${SITE_DESC}

## Notes

${notes
  .map((n) => `- [${n.title}](${noteUrl(n.slug)}): ${n.blurb}`)
  .join("\n")}

## Elsewhere

${ELSEWHERE.map((e) =>
  e.description
    ? `- [${e.title}](${e.url}): ${e.description}`
    : `- [${e.title}](${e.url})`,
).join("\n")}
`;
}

function llmsFullTxt() {
  return `# ${SITE_NAME}

> ${SITE_DESC}

## About

Software engineer by craft, founder by trade, technology enthusiast by
practice. Currently building TurboDocx (https://www.turbodocx.com) and
writing from the South Florida coast.

Now: Founder, TurboDocx
Before: Startups, Okta/Auth0, Citrix, FlexShopper, UKG
Where: Somewhere between Palm Beach County and Miami-Dade
Status: Heads down, building

## Notes

${notes
  .map(
    (n) => `### ${n.title}

URL: ${noteUrl(n.slug)}
Filed: ${n.date}
Topic: ${n.topic}
Reading time: ${n.read}

${n.blurb}

_Full content placeholder — real essay body lands when published._
`,
  )
  .join("\n")}

## Elsewhere

${ELSEWHERE.map((e) =>
  e.description ? `- ${e.title} (${e.url}): ${e.description}` : `- ${e.title} (${e.url})`,
).join("\n")}
`;
}

const ROUTE_PRELUDE = `// AUTO-GENERATED by scripts/generate-llms.mjs — do not edit by hand.
// Regenerated on every build via the "prebuild" npm script.
export const dynamic = "force-static";\n\n`;

function plainTextRoute(body) {
  return `${ROUTE_PRELUDE}export function GET() {
  return new Response(\`${js(body)}\`, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
`;
}

function markdownRoute(body) {
  return `${ROUTE_PRELUDE}export function GET() {
  return new Response(\`${js(body)}\`, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
}
`;
}

console.log("🤖 Generating LLM routes from lib/notes.json...");
write("app/llms.txt/route.ts", plainTextRoute(llmsTxt()));
write("app/llms-full.txt/route.ts", plainTextRoute(llmsFullTxt()));
write("app/index.html.md/route.ts", markdownRoute(homeMarkdown()));
write("app/notes.html.md/route.ts", markdownRoute(notesArchiveMarkdown()));
// One literal .html.md route per note. Sibling to /notes/[slug] — Next prefers
// literal segments over dynamic ones, so /notes/<slug>.html.md/ resolves here
// while /notes/<slug>/ keeps hitting the page route.
for (const n of notes) {
  write(
    `app/notes/${n.slug}.html.md/route.ts`,
    markdownRoute(noteMarkdown(n)),
  );
}
console.log(
  `✅ Generated ${4 + notes.length} static routes ` +
    `(${notes.length} per-note MDs).`,
);
